# Use root/example as user/password credentials
version: '3.1'


volumes:
  db_data: {}

services:

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql    
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  library:
    depends_on:
      - db
    image: library
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - 5010:5000

